global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'PostTechFiap.Api'
    scheme: https
    tls_config:
      insecure_skip_verify: true
    static_configs:
      - targets:
          - 'posttechfiap.api:8443'

  - job_name: 'node-exporter'
    static_configs:
      - targets: 
          - 'node-exporter:9100'
          