# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: CD

on:
  workflow_dispatch:

jobs:
  Build-API:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Build with dotnet
        run: dotnet build HealthMed_Hackaton.sln --configuration Release

      - name: dotnet publish HealthMed-API
        run: dotnet publish ./HealthMed.Presentation/HealthMed.Presentation.csproj -c Release -o ${{env.DOTNET_ROOT}}/api

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: HealthMed-API
          path: ${{env.DOTNET_ROOT}}/api
          
  Build-Agendamentos:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Build with dotnet
        run: dotnet build HealthMed_Hackaton.sln --configuration Release

      - name: dotnet publish HealthMed-Agendamentos
        run: dotnet publish ./WebJobs/HealthMed.Agendamentos/HealthMed.Agendamentos.csproj -c Release -o ${{env.DOTNET_ROOT}}/agendamentos

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: HealthMed-Agendamentos
          path: ${{env.DOTNET_ROOT}}/agendamentos

  Build-Notificacoes:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Build with dotnet
        run: dotnet build HealthMed_Hackaton.sln --configuration Release

      - name: dotnet publish HealthMed-Notificacoes
        run: dotnet publish ./WebJobs/HealthMed.Notificacoes/HealthMed.Notificacoes.csproj -c Release -o ${{env.DOTNET_ROOT}}/notificacoes

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: HealthMed-notificacoes
          path: ${{env.DOTNET_ROOT}}/notificacoes


  Deploy-API:
    runs-on: ubuntu-latest
    needs: Build-Api
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: HealthMed-API
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_CD587F61CF514513841AFCB1DF9FED79 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_633E5470359743BAAF5D3CCDE57984D6 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_5BD4B977096748599FDFD431D8CE5D15 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'HealthMed-API'
          slot-name: 'Production'
          package: .
    
  Deploy-Agendamentos:
    runs-on: ubuntu-latest
    needs: Build-Agendamentos
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: HealthMed-Agendamentos
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_02EC686F1FCF4668BECE537ADD77F482 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_601F17F73E6344B9A6E04076D81441C0 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_1B04FE6D69A64C9CA5F776F6C1D5129F }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'HealthMed-Agendamentos'
          slot-name: 'Production'
          package: .

  Deploy-Notificacoes:
    runs-on: ubuntu-latest
    needs: Build-Notificacoes
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_936CAA2608A84C81BE24DC2AF258B696 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_DBABA27DD9BC4792AC4BD59E090D511D }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_FB9DB07589D4408DA6974FE7FCB25696 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'HealthMed-Notificacoes'
          slot-name: 'Production'
          package: .
